<?php

class ProductsTableSeeder extends Seeder {

    public function run()
    {
    	// Uncomment the below to wipe the table clean before populating
    	DB::table('products')->delete();

        $products = array
        (
        	array('name' => 'Msuit1','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit006.jpg','image2' => 'suit008.jpg','image3' => 'suit004.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => '28""','prop4' => '32""',),
        	array('name' => 'Msuit2','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit004.jpg','image2' => 'suit008.jpg','image3' => 'suit001.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit3','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit003.jpg','image2' => 'suit001.jpg','image3' => 'suit009.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit4','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit000.jpg','image2' => 'suit005.jpg','image3' => 'suit001.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit5','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit003.jpg','image2' => 'suit009.jpg','image3' => 'suit003.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit6','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit004.jpg','image2' => 'suit006.jpg','image3' => 'suit009.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit7','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit004.jpg','image2' => 'suit001.jpg','image3' => 'suit007.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit8','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit009.jpg','image2' => 'suit006.jpg','image3' => 'suit005.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit9','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit007.jpg','image2' => 'suit001.jpg','image3' => 'suit002.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit10','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit002.jpg','image2' => 'suit004.jpg','image3' => 'suit007.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit11','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit003.jpg','image2' => 'suit008.jpg','image3' => 'suit003.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit12','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit007.jpg','image2' => 'suit004.jpg','image3' => 'suit007.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit13','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit005.jpg','image2' => 'suit007.jpg','image3' => 'suit001.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit14','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit009.jpg','image2' => 'suit004.jpg','image3' => 'suit002.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit15','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit007.jpg','image2' => 'suit002.jpg','image3' => 'suit000.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit16','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit005.jpg','image2' => 'suit005.jpg','image3' => 'suit007.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit17','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit005.jpg','image2' => 'suit002.jpg','image3' => 'suit006.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit18','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit001.jpg','image2' => 'suit001.jpg','image3' => 'suit007.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit19','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit008.jpg','image2' => 'suit007.jpg','image3' => 'suit002.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit20','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit004.jpg','image2' => 'suit005.jpg','image3' => 'suit002.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit21','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit000.jpg','image2' => 'suit007.jpg','image3' => 'suit001.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit22','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit000.jpg','image2' => 'suit005.jpg','image3' => 'suit009.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit23','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit008.jpg','image2' => 'suit007.jpg','image3' => 'suit005.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit24','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit002.jpg','image2' => 'suit006.jpg','image3' => 'suit004.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit25','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit000.jpg','image2' => 'suit002.jpg','image3' => 'suit002.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit26','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit009.jpg','image2' => 'suit002.jpg','image3' => 'suit002.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit27','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit000.jpg','image2' => 'suit000.jpg','image3' => 'suit002.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit28','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit001.jpg','image2' => 'suit004.jpg','image3' => 'suit001.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit29','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit006.jpg','image2' => 'suit001.jpg','image3' => 'suit008.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	array('name' => 'Msuit30','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet massa sem.','category_id' => 1,'vendor_id' => 1,'image1' => 'suit004.jpg','image2' => 'suit009.jpg','image3' => 'suit000.jpg','minunits' => 10,'maxunits' => 100,'prop1' => 'Cotton','prop2' => 'Red','prop3' => 28,'prop4' => 32,),
        	
		);

        // Uncomment the below to run the seeder
        DB::table('products')->insert($products);
    }

}